query ArticleFromSlug($slug: String!) {
  articleCollection(where: { slug: $slug }) {
    items {
      slug,
      title,
      description,
      thumbnail {
        title,
        url,
      },
      sys {
        publishedAt,
      },
    }
  }
}
