query ArticleCollection {
  articleCollection {
    items {
      slug,
      title,
      description,
      thumbnail {
        title,
        url,
      },
      sys {
        publishedAt,
      },
    }
  }
}
