import cn from 'classnames'
import Image from 'next/image'
import { Feature } from '../schemas/contentful/types'

type Props = {
  className?: string
  features: Feature[]
}

const FeatureList = ({ className, features }: Props) => {
  return (
    <div
      className={cn(
        'grid grid-cols-1 md:grid-cols-3 gap-24 md:gap-10',
        className,
      )}
    >
      {features.map((feature) => (
        <div key={feature.title} className="flex flex-col gap-5">
          <div className="flex flex-col items-center justify-center gap-8">
            <Image
              src={feature.image.url}
              alt={feature.image.alt}
              width={feature.image.width}
              height={feature.image.height}
              style={{
                filter:
                  // Generated by https://codepen.io/sosuke/pen/Pjoqqp
                  'invert(53%) sepia(99%) saturate(359%) hue-rotate(121deg) brightness(86%) contrast(88%)',
              }}
              className="w-48 md:w-40"
            />
            <h3 className="text-4xl md:text-3xl font-bold md:text-center">
              {feature.title}
            </h3>
          </div>
          <p>{feature.content}</p>
        </div>
      ))}
    </div>
  )
}

export default FeatureList
