fragment article on Article {
  slug
  title
  excerpt
  content
  date
  dateEnd
  dateIsContinue
  company
  githubRepo
  image {
    ...image
  }
  category {
    ...tag
  }
  tagCollection {
    items {
      ...tag
    }
  }
  sys {
    id
    publishedAt
  }
}
