fragment article on Article {
  slug
  title
  excerpt
  content
  date
  dateEnd
  dateIsContinue
  githubRepo
  image {
    title
    url
  }
  category {
    ...tag
  }
  tagCollection {
    items {
      ...tag
    }
  }
  sys {
    id
    publishedAt
  },
}
