fragment intro on Intro {
  title
  content
  firstName
  firstNameRuby
  lastName
  lastNameRuby
  position
  githubUrl
  catchTitle
  catchDescription
  featureTitle
  featureDescription
  portraitImage {
    ...image
  }
  backgroundImage {
    ...image
  }
  featureCollection(limit: 3) {
    items {
      title
      content
      image {
        ...image
      }
    }
  }
}
