query ArticleFromSlug($slug: String!) {
  articleCollection(where: { slug: $slug }) {
    items {
      slug,
      title,
      excerpt,
      content,
      image {
        title,
        url,
      },
      tagCollection {
        items {
          slug,
          title,
        },
      },
      sys {
        publishedAt,
      },
    }
  }
}
