query getTagWithGroupCollection {
  tagCollection {
    items {
      ...tag
      tagGroup {
        title
      }
      linkedFrom {
        articleCollection {
          total
        }
      }
    }
  }
}
